[phases.setup]
nixPkgs = ["...", "ffmpeg", "php81", "perl", "nginx", "php81Packages.composer"]

[phases.install]
cmds = ["mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx", "composer install --ignore-platform-reqs"]


